function displayPoem(response) {
  new Typewriter("#poem", {
    strings: response.data.answer,
    autoStart: true,
    delay: 1,
    cursor: "",
  });
}

function generatePoem(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#instructions");

  let apiKey = "24b9b3ae0f6ea728ao45f6et261b0962";
  let prompt = `Generate an African American poem about ${instructionsInput.value}`;
  let context =
    "User instructions: You are an expert in African American poetry and love to write very short poems. Your mission is to generate a 4 line poem in basic HTML without a title.  Sign the poem as 'Generated by Maya Claros for SheCodes AI' inside a <strong> element at the end of the poem";
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&key=${apiKey}`;

  let poemElement = document.querySelector("#poem");
  poemElement.classList.remove("hidden");
  poemElement.innerHTML = `<div class="generating">⌛️ Generating an African American poem about ${instructionsInput.value}</div>`;

  console.log("generating poem");
  axios.get(apiUrl).then(displayPoem);
}

let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);
